---
sudo: false
dist: xenial
language: python
cache: pip

services:
  - mysql

python:
  - '3.6'
  - '3.7'

env:
  matrix:
    - DJANGO=1.11
    - DJANGO=2.0
    - DJANGO=2.1

matrix:
  fast_finish: true
  include:
    - {python: '3.7', env: TOXENV=lint}

install:
  - travis_retry pip install --upgrade pip tox tox-venv tox-travis

script:
  - tox || travis_terminate 1

notifications:
  email: false

deploy:
  provider: pypi
  user: managedbyq
  password:
    secure: rT8H1dxcyyl5mCwvnEnKpb7VvtJ62B5wHRitGxs6We/01pXEpLj0cMl51mwTBrojX/kyLwZpH6Xrjz5q56qr/iYu10CCtd5Q60KwHNkZNhxQYaKADcGORTzpqBX7r83FeJQLIpBDroudWUQhe78x9xcl6NFLowXrJvTLQdEu950TofI8XT8/i3lzTlQ8QentMDqtSBzFq5XyUAK0Zn426MDp7hHzNxJfTUh+a2sCpuSnHyM590TsAs4EVHCQcLPhjbOqFzposU5tWku6iHsepvod1caHSEuvrifnpyztkVO41e0q0iZPgFFBKWOqpqrLqly8bi1k+4jcJXkxkmNRPQ0HZd0YH10wApg/nqE8+v6aOdUZmDu+y26NvduGH8HmDm16IOWKRfEsKWHiaqBw9Y94ELy38op0J7c6KcF2vMwM+VHo1YHiaEOxdzSx9I8awHsU043x1PxVB2l5i4WPs1eyogQ5CpIqpHFp7fG8NuINmpv3P/myBB7L2ZtIu062ibL7/syTRrxRXdR8YoWWdgtnRd7Ndpq5kZm1HYiuBwCy4h/sm+DAs5UX7jcVJcI38G7578ru+BF/hSBbkX/cUf+jNzZB0qHxqGP/HpHIsTEvU4hTUguOfmaxwQowsikOQzq7DmQLZ2ocjO2fVjY2wtpxhacF5Z1AxszkWIJ0xVE=
  on:
    repo: managedbyq/mbq.ranch
    branch: master
    tags: true
    python: '3.6'
    # admittedly, this condition is a bit silly but we want the deploy to happen
    # on exactly one build, not all py36 builds, and looking for django 1.11 is
    # a cheap way to accomplish that.
    condition: $DJANGO = '1.11'
    distributions: sdist bdist_wheel
