---
version: '3'

services:
  py36:
    build:
      context: .
      args:
        IMAGE: 'python:3.6-stretch'
    volumes:
      - .:/app
    links:
      - mysql
    environment:
      TOX_WORK_DIR: /tox
      PYTHON_VERSION: py36

  py37:
    build:
      context: .
      args:
        IMAGE: 'python:3.7-stretch'
    volumes:
      - .:/app
    links:
      - mysql
    environment:
      TOX_WORK_DIR: /tox
      PYTHON_VERSION: py37

  mysql:
    image: mysql:5.6
    environment:
      - MYSQL_DATABASE=ranchdb
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
